services:
  worker-manager:
    build:
      context: ./Go
      dockerfile: ./cmd/WorkerManager/Dockerfile
    image: jmorneau/xka-worker-manager:${IMAGE_TAG:-latest}
    ports:
      - "8080:8080"
    env_file:
      - .env
    environment:
      - ENV=production 
    depends_on:
      - redis
      - postgres                     
    healthcheck:
      test: ["CMD", "curl", "-f", "http://localhost:8080/"]
      interval: 10s
      timeout: 3s
      retries: 5
      start_period: 5s

  worker:
    build:
      context: ./Go
      dockerfile: ./cmd/worker/Dockerfile
    image: jmorneau/xka-worker:${IMAGE_TAG:-latest}
    env_file:
      - .env
    environment:
      - ENV=production
    depends_on:
      - redis
      - postgres

  redis:
    image: redis:7-alpine
    ports:
      - "6379:6379"
    volumes:
      - redis-data:/data

  postgres:
    image: postgres:16-alpine
    ports:
      - "5432:5432"
    environment:
      - POSTGRES_DB=xka
      - POSTGRES_USER=xka_user
      - POSTGRES_PASSWORD=xka_password
    volumes:
      - postgres-data:/var/lib/postgresql/data
      - ./Go/migrations:/docker-entrypoint-initdb.d
    healthcheck:
      test: ["CMD-SHELL", "pg_isready -U xka_user -d xka"]
      interval: 10s
      timeout: 5s
      retries: 5

volumes:
  redis-data:
  postgres-data:
  pgadmin-data: