services:
  worker-manager:
    build:
      context: ./Go
      dockerfile: ./cmd/WorkerManager/Dockerfile
    image: jmorneau/xka-worker-manager:${IMAGE_TAG}
    ports:
      - "8080:8080"
    env_file:
      - .env  
    environment:
      - ENV=production 
    depends_on:
      - redis                     
    healthcheck:
      test: ["CMD", "curl", "-f", "http://localhost:8080/"]
      interval: 10s
      timeout: 3s
      retries: 5
      start_period: 5s

  worker:
    build:
      context: ./Go
      dockerfile: ./cmd/worker/Dockerfile
    image: jmorneau/xka-worker:${IMAGE_TAG}
    env_file:
      - .env  
    environment:
      - ENV=production
    depends_on:
      - redis

  redis:
    image: redis:7-alpine
    ports:
      - "6379:6379"
    volumes:
      - redis-data:/data

volumes:
  redis-data:
