// Code generated by ent, DO NOT EDIT.

package ent

import (
	"XKA/ent/schema"
	"XKA/ent/workflow"
	"XKA/ent/workflowexecutionresult"
	"time"

	"github.com/google/uuid"
)

// The init function reads all schema descriptors with runtime code
// (default values, validators, hooks and policies) and stitches it
// to their package variables.
func init() {
	workflowMixin := schema.Workflow{}.Mixin()
	workflowMixinFields0 := workflowMixin[0].Fields()
	_ = workflowMixinFields0
	workflowFields := schema.Workflow{}.Fields()
	_ = workflowFields
	// workflowDescCreateTime is the schema descriptor for create_time field.
	workflowDescCreateTime := workflowMixinFields0[0].Descriptor()
	// workflow.DefaultCreateTime holds the default value on creation for the create_time field.
	workflow.DefaultCreateTime = workflowDescCreateTime.Default.(func() time.Time)
	// workflowDescUpdateTime is the schema descriptor for update_time field.
	workflowDescUpdateTime := workflowMixinFields0[1].Descriptor()
	// workflow.DefaultUpdateTime holds the default value on creation for the update_time field.
	workflow.DefaultUpdateTime = workflowDescUpdateTime.Default.(func() time.Time)
	// workflow.UpdateDefaultUpdateTime holds the default value on update for the update_time field.
	workflow.UpdateDefaultUpdateTime = workflowDescUpdateTime.UpdateDefault.(func() time.Time)
	// workflowDescName is the schema descriptor for name field.
	workflowDescName := workflowFields[1].Descriptor()
	// workflow.NameValidator is a validator for the "name" field. It is called by the builders before save.
	workflow.NameValidator = workflowDescName.Validators[0].(func(string) error)
	// workflowDescID is the schema descriptor for id field.
	workflowDescID := workflowFields[0].Descriptor()
	// workflow.DefaultID holds the default value on creation for the id field.
	workflow.DefaultID = workflowDescID.Default.(func() uuid.UUID)
	workflowexecutionresultMixin := schema.WorkflowExecutionResult{}.Mixin()
	workflowexecutionresultMixinFields0 := workflowexecutionresultMixin[0].Fields()
	_ = workflowexecutionresultMixinFields0
	workflowexecutionresultFields := schema.WorkflowExecutionResult{}.Fields()
	_ = workflowexecutionresultFields
	// workflowexecutionresultDescCreateTime is the schema descriptor for create_time field.
	workflowexecutionresultDescCreateTime := workflowexecutionresultMixinFields0[0].Descriptor()
	// workflowexecutionresult.DefaultCreateTime holds the default value on creation for the create_time field.
	workflowexecutionresult.DefaultCreateTime = workflowexecutionresultDescCreateTime.Default.(func() time.Time)
	// workflowexecutionresultDescUpdateTime is the schema descriptor for update_time field.
	workflowexecutionresultDescUpdateTime := workflowexecutionresultMixinFields0[1].Descriptor()
	// workflowexecutionresult.DefaultUpdateTime holds the default value on creation for the update_time field.
	workflowexecutionresult.DefaultUpdateTime = workflowexecutionresultDescUpdateTime.Default.(func() time.Time)
	// workflowexecutionresult.UpdateDefaultUpdateTime holds the default value on update for the update_time field.
	workflowexecutionresult.UpdateDefaultUpdateTime = workflowexecutionresultDescUpdateTime.UpdateDefault.(func() time.Time)
	// workflowexecutionresultDescNumberOfNodes is the schema descriptor for number_of_nodes field.
	workflowexecutionresultDescNumberOfNodes := workflowexecutionresultFields[9].Descriptor()
	// workflowexecutionresult.DefaultNumberOfNodes holds the default value on creation for the number_of_nodes field.
	workflowexecutionresult.DefaultNumberOfNodes = workflowexecutionresultDescNumberOfNodes.Default.(int)
	// workflowexecutionresultDescID is the schema descriptor for id field.
	workflowexecutionresultDescID := workflowexecutionresultFields[0].Descriptor()
	// workflowexecutionresult.DefaultID holds the default value on creation for the id field.
	workflowexecutionresult.DefaultID = workflowexecutionresultDescID.Default.(func() uuid.UUID)
}
