// Code generated by ent, DO NOT EDIT.

package migrate

import (
	"entgo.io/ent/dialect/sql/schema"
	"entgo.io/ent/schema/field"
)

var (
	// WorkflowsColumns holds the columns for the "workflows" table.
	WorkflowsColumns = []*schema.Column{
		{Name: "id", Type: field.TypeUUID, Unique: true},
		{Name: "create_time", Type: field.TypeTime},
		{Name: "update_time", Type: field.TypeTime},
		{Name: "name", Type: field.TypeString},
	}
	// WorkflowsTable holds the schema information for the "workflows" table.
	WorkflowsTable = &schema.Table{
		Name:       "workflows",
		Columns:    WorkflowsColumns,
		PrimaryKey: []*schema.Column{WorkflowsColumns[0]},
	}
	// WorkflowExecutionResultsColumns holds the columns for the "workflow_execution_results" table.
	WorkflowExecutionResultsColumns = []*schema.Column{
		{Name: "id", Type: field.TypeUUID, Unique: true},
		{Name: "create_time", Type: field.TypeTime},
		{Name: "update_time", Type: field.TypeTime},
		{Name: "status", Type: field.TypeEnum, Enums: []string{"success", "error", "running", "skipped"}},
		{Name: "started_at", Type: field.TypeInt64},
		{Name: "ended_at", Type: field.TypeInt64, Nullable: true},
		{Name: "duration_ms", Type: field.TypeInt64, Nullable: true},
		{Name: "global_logs", Type: field.TypeJSON, Nullable: true},
		{Name: "error", Type: field.TypeString, Nullable: true},
		{Name: "meta", Type: field.TypeJSON, Nullable: true},
		{Name: "number_of_nodes", Type: field.TypeInt, Default: 0},
		{Name: "workflow_id", Type: field.TypeUUID},
	}
	// WorkflowExecutionResultsTable holds the schema information for the "workflow_execution_results" table.
	WorkflowExecutionResultsTable = &schema.Table{
		Name:       "workflow_execution_results",
		Columns:    WorkflowExecutionResultsColumns,
		PrimaryKey: []*schema.Column{WorkflowExecutionResultsColumns[0]},
		ForeignKeys: []*schema.ForeignKey{
			{
				Symbol:     "workflow_execution_results_workflows_execution_results",
				Columns:    []*schema.Column{WorkflowExecutionResultsColumns[11]},
				RefColumns: []*schema.Column{WorkflowsColumns[0]},
				OnDelete:   schema.NoAction,
			},
		},
	}
	// Tables holds all the tables in the schema.
	Tables = []*schema.Table{
		WorkflowsTable,
		WorkflowExecutionResultsTable,
	}
)

func init() {
	WorkflowExecutionResultsTable.ForeignKeys[0].RefTable = WorkflowsTable
}
