// Code generated by ent, DO NOT EDIT.

package predicate

import (
	"entgo.io/ent/dialect/sql"
)

// Workflow is the predicate function for workflow builders.
type Workflow func(*sql.Selector)

// WorkflowExecutionResult is the predicate function for workflowexecutionresult builders.
type WorkflowExecutionResult func(*sql.Selector)
