name: Docker Compose Build & Push CI

on:
  push:
    branches: ["master"]
  pull_request:
    branches: ["master"]

# Éviter les builds redondants
concurrency:
  group: ${{ github.workflow }}-${{ github.ref }}
  cancel-in-progress: true

jobs:
  build-and-push:
    runs-on: ubuntu-latest
    environment: production
    
    steps:
      - name: Checkout code
        uses: actions/checkout@v4

      - name: Set up Docker Buildx
        uses: docker/setup-buildx-action@v3
        with:
          driver-opts: network=host

      # Ne se connecter que pour les push vers master (pas pour les PRs)
      - name: Log in to DockerHub
        if: github.event_name == 'push' && github.ref == 'refs/heads/master'
        uses: docker/login-action@v3
        with:
          username: ${{ secrets.DOCKERHUB_USERNAME }}
          password: ${{ secrets.DOCKERHUB_TOKEN }}

      - name: Create .env file
        run: touch .env

      # Générer les métadonnées pour le tagging
      - name: Extract metadata
        id: meta
        run: |
          echo "date=$(date +'%Y%m%d')" >> $GITHUB_OUTPUT
          echo "sha_short=$(echo ${{ github.sha }} | cut -c1-7)" >> $GITHUB_OUTPUT
          echo "ref_name=${GITHUB_REF#refs/heads/}" >> $GITHUB_OUTPUT

      - name: Build images via compose
        run: docker compose -f docker-compose.yml build --parallel
        env:
          DOCKER_BUILDKIT: 1
          COMPOSE_DOCKER_CLI_BUILD: 1
          # Variables pour le tagging
          IMAGE_TAG: ${{ steps.meta.outputs.sha_short }}
          BUILD_DATE: ${{ steps.meta.outputs.date }}

      # Test rapide des images avant push
      - name: Test images
        run: |
          echo "Testing built images..."
          docker compose -f docker-compose.yml config --quiet
          # Ajouter ici d'autres tests si nécessaire
          # docker compose -f docker-compose.yml run --rm service_name test

      # Ne push que sur master, pas sur les PRs
      - name: Push images to DockerHub
        if: github.event_name == 'push' && github.ref == 'refs/heads/master'
        run: docker compose -f docker-compose.yml push
        env:
          IMAGE_TAG: ${{ steps.meta.outputs.sha_short }}

      # Nettoyage automatique
      - name: Clean up Docker resources
        if: always()
        run: |
          docker compose -f docker-compose.yml down --volumes --remove-orphans || true
          docker system prune -f --volumes || true